In [1]:
import pandas as pd

In [3]:
df= pd.DataFrame({
    "Order data":[
        "2024-01-18",
        "2024-01-15",
        "2024-02-05",
        "2024-02-12",
        "2024-03-01",
        "2024-03-15",
        "2024-04-10",
        "2024-04-20",
        "2024-05-05",
        "2024-01-15"
    ],
    
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Laptop",
        "Monitor",
        "Mouse",
        "Printer",
        "Smartwatch",
        "Mouse"
    ],
    
    "Category":[
        "Electronics",
        "Accessories",
        "Office",
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Office",
        "Electronics",
        "Accessories"
    ],
    
    
    "Region": [
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "west",
        "North",
        "South"
    ],
    
    "Quantity":[
        2,
        5,
        3,
        4,
        1,
        2,
        6,
        2,
        3,
        5
    ],
    
    
    "Sales":[
        50000,
        2500,
        9000,
        30000,
        55000,
        16000,
        3000,
        6000,
        45000,
        2500
    ],
    
    "Profit":[
        10000,
        500,
        1500,
        6000,
        11000,
        3000,
        None,
        1000,
        9000,
        500
    ]
})

print("1.ORIGINAL DATASET")
print("-" * 50)
display(df)

1.ORIGINAL DATASET
--------------------------------------------------

   Order data Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-18       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5  2024-03-15      Monitor  Accessories  South         2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East         6   3000      NaN
7  2024-04-20      Printer       Office   west         2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South         5   2500    500.0

In [4]:
print("2.FIRST 5 RECORDS")
print("_" * 50)
display(df.head())

2.FIRST 5 RECORDS
__________________________________________________

   Order data Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-18       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0

In [6]:
print("3. DATA SET SHAPE")
print("-" * 50)
display(df.shape)

3. DATA SET SHAPE
--------------------------------------------------

(10, 7)

In [7]:
print("4.DATASET COLUMNS")
print("-"*50)
display(df.columns)

4.DATASET COLUMNS
--------------------------------------------------

Index(['Order data', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='object')

In [8]:
print("5.DATA TYPES")
print("-"*50)
display(df.dtypes)

5.DATA TYPES
--------------------------------------------------

Order data       object
Product Name     object
Category         object
Region           object
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [10]:
print("6.DESCRIPTIVE STATISTICS")
print("-"*50)
display(df.describe())

6.DESCRIPTIVE STATISTICS
--------------------------------------------------

        Quantity         Sales        Profit
count  10.000000     10.000000      9.000000
mean    3.300000  21900.000000   4722.222222
std     1.636392  21209.012759   4330.928820
min     1.000000   2500.000000    500.000000
25%     2.000000   3750.000000   1000.000000
50%     3.000000  12500.000000   3000.000000
75%     4.750000  41250.000000   9000.000000
max     6.000000  55000.000000  11000.000000

In [13]:
print("7.MISSING VALUES")
print("-"*50)
display(df.isnull().sum())

7.MISSING VALUES
--------------------------------------------------

Order data      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          1
dtype: int64

In [15]:
print("8.ROWS CONTAINING MISSING VALUES")
print("-"*50)
display(df[df.isnull().any(axis=1)])

8.ROWS CONTAINING MISSING VALUES
--------------------------------------------------

   Order data Product Name     Category Region  Quantity  Sales  Profit
6  2024-04-10        Mouse  Accessories   East         6   3000     NaN

In [17]:
print("9.TOTAL DUPLICATE RECORD")
print("-"*50)
display(df.duplicated().sum())

9.TOTAL DUPLICATE RECORD
--------------------------------------------------

1

In [18]:
print("10.DUPLICATE RECORD")
print("-"*50)
display(df[df.duplicated()])

10.DUPLICATE RECORD
--------------------------------------------------

   Order data Product Name     Category Region  Quantity  Sales  Profit
9  2024-01-15        Mouse  Accessories  South         5   2500   500.0

In [20]:
new_sales = pd.DataFrame({
    
    "Order Data":[
        "2024-06-01",
        "2024-06-05",
        "2024-06-10"
    ],
    
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer"
    ],
    
    "Category":[
        "Electronics",
        "Accessories",
        "Office"
    ],
    
    "Region":[
        "North",
        "South",
        "East"
    ],
    
    "Quantity":[
        2,
        3,
        4
    ],
    
    "Sales":[
        60000,
        2000,
        9000
    ],
    
    "Profit":[
        12000,
        400,
        1800
    ]
})

print("11.NEW SALES DATAFRAME")
print("-"*50)
display(new_sales)

11.NEW SALES DATAFRAME
--------------------------------------------------

   Order Data Product Name     Category Region  Quantity  Sales  Profit
0  2024-06-01       Laptop  Electronics  North         2  60000   12000
1  2024-06-05        Mouse  Accessories  South         3   2000     400
2  2024-06-10      Printer       Office   East         4   9000    1800

In [21]:
combined_df = pd.concat(
    [df,new_sales],
    ignore_index=True
)

In [22]:
print("12.CONCATINATED DATAFRAME")
print("-"*50)
display(combined_df)

12.CONCATINATED DATAFRAME
--------------------------------------------------

,Order data,Product Name,Category,Region,Quantity,Sales,Profit,Order Data
0,2024-01-18,Laptop,Electronics,North,2,50000,10000.0,NaN
1,2024-01-15,Mouse,Accessories,South,5,2500,500.0,NaN
2,2024-02-05,Printer,Office,East,3,9000,1500.0,NaN
3,2024-02-12,Tablet,Electronics,West,4,30000,6000.0,NaN
4,2024-03-01,Laptop,Electronics,North,1,55000,11000.0,NaN
5,2024-03-15,Monitor,Accessories,South,2,16000,3000.0,NaN
6,2024-04-10,Mouse,Accessories,East,6,3000,NaN,NaN
7,2024-04-20,Printer,Office,west,2,6000,1000.0,NaN
8,2024-05-05,Smartwatch,Electronics,North,3,45000,9000.0,NaN
9,2024-01-15,Mouse,Accessories,South,5,2500,500.0,NaN
10,NaN,Laptop,Electronics,North,2,60000,12000.0,2024-06-01
11,NaN,Mouse,Accessories,South,3,2000,400.0,2024-06-05
12,NaN,Printer,Office,East,4,9000,1800.0,2024-06-10

In [23]:
product_info=pd.DataFrame({
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Monitor"
    ],
    
    "Supplier":[
        "Dell",
        "Logitech",
        "HP",
        "Samsung",
        "LG"
    ],
    
    
    "Discount":[
        10,
        5,
        15,
        8,
        12
    ]
})

print("13.PRODUCT INFORMATION DATAFRAME")
print("-"*50)
display(product_info)

13.PRODUCT INFORMATION DATAFRAME
--------------------------------------------------

  Product Name  Supplier  Discount
0       Laptop      Dell        10
1        Mouse  Logitech         5
2      Printer        HP        15
3       Tablet   Samsung         8
4      Monitor        LG        12

In [24]:
merged_df=pd.merge(
    df,
    product_info,
    on="Product Name",
    how="left"
)

print("14.MAERGED DATAFRAME")
print("-"*50)
display(merged_df)

14.MAERGED DATAFRAME
--------------------------------------------------

,Order data,Product Name,Category,Region,Quantity,Sales,Profit,Supplier,Discount
0,2024-01-18,Laptop,Electronics,North,2,50000,10000.0,Dell,10.0
1,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0
2,2024-02-05,Printer,Office,East,3,9000,1500.0,HP,15.0
3,2024-02-12,Tablet,Electronics,West,4,30000,6000.0,Samsung,8.0
4,2024-03-01,Laptop,Electronics,North,1,55000,11000.0,Dell,10.0
5,2024-03-15,Monitor,Accessories,South,2,16000,3000.0,LG,12.0
6,2024-04-10,Mouse,Accessories,East,6,3000,NaN,Logitech,5.0
7,2024-04-20,Printer,Office,west,2,6000,1000.0,HP,15.0
8,2024-05-05,Smartwatch,Electronics,North,3,45000,9000.0,NaN,NaN
9,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0

In [25]:
region_info=pd.DataFrame({
    "Region_Manager":[
        "Manager A",
        "Manager B",
        "Manager C",
        "Manager D"
        
    ]    
    
},
    
    index=[
        "North",
        "South",
        "East",
        "West"
    ]
)

print("15.REGION INFORMATION")
print("-"*50)
display(region_info)

15.REGION INFORMATION
--------------------------------------------------

      Region_Manager
North      Manager A
South      Manager B
East       Manager C
West       Manager D

In [26]:
df_region = df.set_index("Region")

joined_df = df_region.join(region_info)

print("16.JOINED DATAFRAME")
print("-"*50)
display(joined_df)

16.JOINED DATAFRAME
--------------------------------------------------

,Order data,Product Name,Category,Quantity,Sales,Profit,Region_Manager
Region,,,,,,,
East,2024-02-05,Printer,Office,3,9000,1500.0,Manager C
East,2024-04-10,Mouse,Accessories,6,3000,NaN,Manager C
North,2024-01-18,Laptop,Electronics,2,50000,10000.0,Manager A
North,2024-03-01,Laptop,Electronics,1,55000,11000.0,Manager A
North,2024-05-05,Smartwatch,Electronics,3,45000,9000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B
South,2024-03-15,Monitor,Accessories,2,16000,3000.0,Manager B
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B
West,2024-02-12,Tablet,Electronics,4,30000,6000.0,Manager D
west,2024-04-20,Printer,Office,2,6000,1000.0,NaN

In [28]:
region_sales = df.groupby(
    "Region"
)["Sales"].sum()

print("16.TOTAL SALES BY REGION")
print("-"*50)
display(region_sales)

17.TOTAL SALES BY REGION
--------------------------------------------------

Region
East      12000
North    150000
South     21000
West      30000
west       6000
Name: Sales, dtype: int64

In [32]:
pivot_table=pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

print("18.PIVOTE TABLE")
print("-"*50)
display(pivot_table)

AttributeError: module 'pandas' has no attribute 'pivote_table'

In [33]:
pivot_table=pd.pivote_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

print("18.PIVOTE TABLE")
print("-"*50)
display(pivot_table)

AttributeError: module 'pandas' has no attribute 'pivote_table'

In [34]:
pivot_table=pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

print("17.PIVOTE TABLE")
print("-"*50)
display(pivot_table)

18.PIVOTE TABLE
--------------------------------------------------

Region       East   North  South   West  west
Category
Accessories  3000       0  21000      0     0
Electronics     0  150000      0  30000     0
Office       9000       0      0      0  6000